# Generated by Django 6.0.2 on 2026-02-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_notes',
            field=models.TextField(blank=True),
        ),
    ]
