# Generated by Django 6.0.2 on 2026-02-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_customer_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='admin_notes',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.CharField(max_length=100),
        ),
    ]
