# Generated by Django 6.0.2 on 2026-02-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value_en', models.TextField()),
                ('value_hi', models.TextField()),
                ('value_ta', models.TextField()),
            ],
        ),
    ]
